-- 테이블 삭제
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;

--멤버 테이블 생성
CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PWD VARCHAR2(60) NOT NULL,
    NICK_NM VARCHAR2(15),
    MAG_YN CHAR(1) CHECK ( MAG_YN IN ('Y', 'N') ) -- Y: 여 N: 부
);

--멤버 테이블 코멘트
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NICK_NM IS '닉네임';
COMMENT ON COLUMN MEMBER.MAG_YN IS '운영자 여부';

--멤버 테이블 데이터
INSERT INTO MEMBER VALUES ('admin11', 'admin11', '나츠키', 'Y');

--메뉴 관리 테이블 생성
CREATE TABLE MENU(
    MENU_CATE_NO NUMBER PRIMARY KEY,
--    CATE_YN CHAR(1) CHECK ( CATE_YN IN ('Y', 'N') ), -- Y: 여 , N: 부
    MENU_CATE_REF NUMBER DEFAULT 0,
    MENU_TIT VARCHAR2(30) NOT NULL
);

--메뉴 테이블 자기 참조 제약조건 추가
ALTER TABLE MENU ADD CONSTRAINT MENU_REF_FK FOREIGN KEY (MENU_CATE_REF) REFERENCES MENU (MENU_CATE_NO);

COMMENT ON COLUMN MENU.MENU_CATE_NO IS '메뉴 카테고리 번호';
COMMENT ON COLUMN MENU.MENU_CATE_REF IS '메뉴 카테고리 참조번호';
--COMMENT ON COLUMN MENU.CATE_YN IS '카테고리 여부';
COMMENT ON COLUMN MENU.MENU_TIT IS '메뉴 제목';

--메뉴 데이터
INSERT INTO MENU VALUES( 0, 0, '메인' );
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 0, '메뉴 메인카테고리1');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 1, '카테고리1-1');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 1, '카테고리1-2');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 1, '카테고리1-3');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 0, '메뉴 메인카테고리2');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 5, '카테고리2-1');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 5, '카테고리2-2');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 5, '카테고리2-3');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 0, '메뉴 메인카테고리3');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 9, '카테고리3-1');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 9, '카테고리3-2');
INSERT INTO MENU VALUES( (SELECT NVL( MAX (MENU_CATE_NO), 0 )+1 FROM MENU ), 9, '카테고리3-3');

--메뉴 테이블 확인
SELECT * FROM MENU;
SELECT * FROM MENU WHERE MENU_CATE_REF =0 AND MENU_CATE_NO != 0;

-- 게시판 테이블 생성   
CREATE TABLE BOARD(
    B_NO NUMBER PRIMARY KEY,
    MENU_CATE_NO NUMBER(10),
    B_TITLE VARCHAR2(30) NOT NULL,
    B_CNT VARCHAR2(300) NOT NULL,
    B_ORFILE VARCHAR2(50),
    B_REFILE VARCHAR2(50),
    B_DATE DATE DEFAULT SYSDATE,
    B_TAG VARCHAR2(15),
    B_VIEW NUMBER,
    RGBD_ID VARCHAR2(20) ,
    B_USYN CHAR(1),
    CONSTRAINT B_ID_FK FOREIGN KEY (RGBD_ID) REFERENCES MEMBER (ID),
    CONSTRAINT MENU_CATE_NO_FK FOREIGN KEY (MENU_CATE_NO) REFERENCES MENU (MENU_CATE_NO)
);

--게시판 테이블 코멘트
COMMENT ON COLUMN BOARD.B_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.MENU_CATE_NO IS '메뉴 카테고리 번호';
COMMENT ON COLUMN BOARD.B_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.B_CNT IS '게시글 내용';
COMMENT ON COLUMN BOARD.B_ORFILE IS '첨부파일 원본이름';
COMMENT ON COLUMN BOARD.B_REFILE IS '첨부파일 저장이름';
COMMENT ON COLUMN BOARD.B_DATE IS '게시글 작성일자 ';
COMMENT ON COLUMN BOARD.B_TAG IS '게시글 태그';
COMMENT ON COLUMN BOARD.B_VIEW IS '게시글 조회수';
COMMENT ON COLUMN BOARD.RGBD_ID IS '게시글 작성자';
COMMENT ON COLUMN BOARD.B_USYN IS '게시글 사용여부';

--게시판 샘플 내용
--INSERT INTO BOARD 
--VALUE(  
--    ( (SELECT NVL( MAX (B_NO), 0 )+1 FROM BOARD ) 
--     ,1
--     ,'동력은 바로 이것이다', '천고에 사라지지 않는 것이다 이것은 현저하게 일월과 같은 예가 되려니와 그와 같지 못하다 할지라도 '
--     );

--댓글 테이블 생성
CREATE TABLE REPLY(

    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_ID VARCHAR2(20),
    REPLY_CNT VARCHAR2(80) NOT NULL,
    REPLY_LOCK CHAR(1) CHECK( REPLY_LOCK IN ('Y', 'N') ),
    B_NO NUMBER,
    REPLY_REF NUMBER,
    REPLY_SRT NUMBER,
    REPLY_DATE DATE DEFAULT SYSDATE,
    REPLY_USYN CHAR(1)  CHECK( REPLY_USYN IN ('Y', 'N') ),
    MENU_ID VARCHAR2(10),
    CONSTRAINT REPLY_ID_FK FOREIGN KEY (REPLY_ID) REFERENCES MEMBER (ID),
    CONSTRAINT B_NO_FK FOREIGN KEY (B_NO) REFERENCES BOARD (B_NO)
    
);
--댓글 테이블 자기 참조 제약조건 추가
ALTER TABLE REPLY ADD CONSTRAINT REPLY_REF_FK FOREIGN KEY (REPLY_REF) REFERENCES REPLY (REPLY_NO);

--댓글 테이블 코멘트
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN REPLY.REPLY_ID IS '댓글 작성자 아이디';
COMMENT ON COLUMN REPLY.REPLY_CNT IS '댓글 내용';
COMMENT ON COLUMN REPLY.REPLY_LOCK IS '댓글 비밀글 여부';
COMMENT ON COLUMN REPLY.B_NO IS '게시판 글 번호';
COMMENT ON COLUMN REPLY.REPLY_REF IS '참조 글 번호';
COMMENT ON COLUMN REPLY.REPLY_SRT IS '댓글 순서';
COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글 작성일자';
COMMENT ON COLUMN REPLY.REPLY_USYN IS '댓글 사용여부';
COMMENT ON COLUMN REPLY.MENU_ID IS '메뉴 아이디';

--커밋
COMMIT;

--데이터 확인
SELECT * FROM MEMBER;

